{{- if and (not .Values.canary.enabled) (not (eq .Values.istioDomain "")) -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  gateways:
    - istio-system/app-gateway
  hosts:
    - springtrader-{{ .Values.productName }}.{{ .Values.istioDomain }}
  http:
    - match:
        - uri:
            prefix: /spring-nanotrader-services/api/marketSummary
      rewrite:
        uri: /marketsummary
      route:
        - destination:
            host: marketsummary
            port:
              number: {{ .Values.service.port }}
{{- end }}
